
- hosts: host1
  environment:
    orderer0_example_com: "172.21.28.226"
    couchdb0_example_com: "172.21.28.226"
    peer0_org1_example_com: "172.21.28.226"
    kafka0_example_com: "172.21.28.226"
    zookeeper0_example_com: "172.21.28.226"
    orderer1_example_com: "172.21.28.225"
    couchdb1_example_com: "172.21.28.225" 
    peer0_org2_example_com: "172.21.28.225" 
    kafka1_example_com: "172.21.28.225" 
    zookeeper1_example_com: "172.21.28.225" 
    orderer2_example_com: "172.21.28.224"
    couchdb2_example_com: "172.21.28.224" 
    peer0_org3_example_com: "172.21.28.224" 
    kafka2_example_com: "172.21.28.224" 
    zookeeper2_example_com: "172.21.28.224" 
    IMAGE_TAG: "latest"
    COMPOSE_PROJECT_NAME: "test"
  tasks: 
 
 
    - name: stop network
      command: "docker-compose -f  /root/kafka/docker-compose-host1.yaml down --volumes --remove-orphans"  

- hosts: host2
  environment:
    orderer0_example_com: "172.21.28.226"
    couchdb0_example_com: "172.21.28.226"
    peer0_org1_example_com: "172.21.28.226"
    kafka0_example_com: "172.21.28.226"
    zookeeper0_example_com: "172.21.28.226"
    orderer1_example_com: "172.21.28.225"
    couchdb1_example_com: "172.21.28.225" 
    peer0_org2_example_com: "172.21.28.225" 
    kafka1_example_com: "172.21.28.225" 
    zookeeper1_example_com: "172.21.28.225" 
    orderer2_example_com: "172.21.28.224"
    couchdb2_example_com: "172.21.28.224" 
    peer0_org3_example_com: "172.21.28.224" 
    kafka2_example_com: "172.21.28.224" 
    zookeeper2_example_com: "172.21.28.224" 
    IMAGE_TAG: "latest"
    COMPOSE_PROJECT_NAME: "test"
  tasks:
 
        
    - name: stop network
      command: "docker-compose -f  /root/kafka/docker-compose-host2.yaml down --volumes --remove-orphans "

- hosts: host3
  environment:
    orderer0_example_com: "172.21.28.226"
    couchdb0_example_com: "172.21.28.226"
    peer0_org1_example_com: "172.21.28.226"
    kafka0_example_com: "172.21.28.226"
    zookeeper0_example_com: "172.21.28.226"
    orderer1_example_com: "172.21.28.225"
    couchdb1_example_com: "172.21.28.225" 
    peer0_org2_example_com: "172.21.28.225" 
    kafka1_example_com: "172.21.28.225" 
    zookeeper1_example_com: "172.21.28.225" 
    orderer2_example_com: "172.21.28.224"
    couchdb2_example_com: "172.21.28.224" 
    peer0_org3_example_com: "172.21.28.224" 
    kafka2_example_com: "172.21.28.224" 
    zookeeper2_example_com: "172.21.28.224" 
    IMAGE_TAG: "latest"
    COMPOSE_PROJECT_NAME: "test"
  tasks:


      
    - name: stop network
      command: "docker-compose -f  /root/kafka/docker-compose-host3.yaml  down --volumes --remove-orphans"       